version: "3"
services:

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  postgres:
    image: vishnuhdadhich/visit-counter-postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: visit_counter    
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  flaskapp:
    image: vishnuhdadhich/visit-counter-web:latest
    depends_on:
      - redis
      - postgres
    volumes:
      - webdata:/home/flask/app/web
    environment:
      FLASK_DEBUG: 1
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  nginx:
    image: vishnuhdadhich/visit-counter-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - flaskapp
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  pgdata:
  webdata: