apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - image: vishnuhdadhich/visit-counter-web:latest
        name: flaskapp
        volumeMounts:
        - mountPath: /home/flask/app/web
          name: webdata
        env:
        - name: FLASK_DEBUG
          value: "1"
      volumes:  
      - name: webdata
        emptyDir: {} 
