apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: visit
spec:
  type: NodePort
  ports:
  - name: "nginx-service"
    port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: nginx
  
